### ISSUE TITLE
Change the route for .png-s used by lightbox

### ISSUE THREAD

**Issue by terravibe** [themyth92/angular2-lightbox#29]
Hey!

Is there any option to change the route, where the lightbox module try to download it's .png's?
I got now 404, because the module try to download them from here:
http://localhost:3000/img/prev.png
But i collect my assets like this:
http://localhost:3000/assets/img/prev.png

**Comment by themyth92** [comment]
hi, those assets file is loaded from **lightbox.css**. It is inside **node_modules/angular2-lightbox/lightbox.css** and **node_modules/angular2-lightbox/img/*.png**. You can manually copy it and put it somewhere in your working folder, then insert that file url in your html and change the location of those assets file. Also need to copy those `png` files to some folder in your working directory as well.
```html
// index.html
<link href="css/lightbox.css" rel="stylesheets" type="text/css">
```

```css
// lightbox.css
/* Preload images */
body:after {
  content: url(assets/img/close.png) url(assets/img/loading.gif) url(assets/img/prev.png) url(assets/img/next.png);
  display: none;
}
```

**NOTE**: The url may be different depends on where you put the **lightbox.css` file. From the above, the file structure could be like this
```
index.html
css/
  lightbox.css
  assets/
    img/
      prev.png
      loading.gif
      next.png
      close.png
```
